import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#FFF5F0",
		alignItems: "center",
		justifyContent: "space-between",
		paddingVertical: 60,
	},
	logoContainer: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
	},
	logo: {
		fontSize: 120,
		fontWeight: "bold",
		color: "#FF6B35",
		marginBottom: 8,
	},
	appName: {
		fontSize: 32,
		fontWeight: "600",
		color: "#FF6B35",
		letterSpacing: 2,
	},
	buttonContainer: {
		width: "100%",
		paddingHorizontal: 32,
		gap: 16,
	},
	primaryButton: {
		backgroundColor: "#FF6B35",
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#FF6B35",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 4,
	},
	primaryButtonText: {
		color: "#FFFFFF",
		fontSize: 18,
		fontWeight: "600",
	},
	secondaryButton: {
		backgroundColor: "transparent",
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		borderWidth: 2,
		borderColor: "#FF6B35",
	},
	secondaryButtonText: {
		color: "#FF6B35",
		fontSize: 18,
		fontWeight: "600",
	},
	dividerContainer: {
		flexDirection: "row",
		alignItems: "center",
		width: "100%",
		paddingHorizontal: 32,
		marginVertical: 8,
	},
	dividerLine: {
		flex: 1,
		height: 1,
		backgroundColor: "#FFB299",
	},
	dividerText: {
		marginHorizontal: 16,
		color: "#FF6B35",
		fontSize: 14,
		fontWeight: "500",
	},
	googleButton: {
		backgroundColor: "#FFFFFF",
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		flexDirection: "row",
		justifyContent: "center",
		borderWidth: 1,
		borderColor: "#E0E0E0",
		shadowColor: "#000000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
	},
	googleButtonText: {
		color: "#1F1F1F",
		fontSize: 16,
		fontWeight: "600",
		marginLeft: 12,
	},
});
